#!/bin/bash
#SBATCH -t 13:00:00
######SBATCH --reservation=rumc_lab
#SBATCH -N 3
#SBATCH -p gpu

module load python/3.5.2
module load cuda/8.0.44
module load cudnn/8.0-v6.0
module load gcc/4.9.2

pip uninstall -y tensorflow
pip uninstall keras
pip install tensorflow-gpu==1.14 --user
pip install keras==2.1.3 --user
pip install tqdm --user
pip install requests --user
pip install opencv-python --user
pip install Pillow --user
pip install scikit-image --user
module load gcc/4.9.2

ssh -o StrictHostKeyChecking=no -f -N -p 22 -R 5113:localhost:5113 int3
jupyter notebook --no-browser --port 5113
